M48
; DRILL file {KiCad (6.0.4)} date Wed Jun  8 19:20:30 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-08T19:20:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X3.487Y-3.193
X4.149Y-5.206
X4.833Y-3.193
T2
X3.95Y-2.9059
X4.35Y-2.9059
T0
M30
